services:
  app:
    build:
      context: .
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
