services:
  app:
    build:
      context: .
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
    ports:
      - "127.0.0.1:5432:5432"
