services:
  app:
    build:
      context: .
    environment:
      - JDBC_DB_URL=jdbc:postgresql://db:5432/demo
      - DB_USER=postgres
    secrets:
      # Grant access to db-password file
      - db-password
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    user: postgres
    secrets:
      # Grant access to db-password file
      - db-password
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=postgres
      # Configure postgresql to get the password from db-password file
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  # Define db-password file as a secret container
  db-password:
    file: db/password.txt
